name: effin-design-system Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn --frozen-lockfile --no-progress --non-interactive --prefer-offline

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - uses: actions/action-dsd-release@v0.0.3
        with:
          api-token: ${{ secrets.DSD_API_TOKEN }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          component-id: 3ekDBovxH09957LsX1ed
          version: ${{ env.PROJECT_VERSION }} # set manually, obtained from a tag or computed
      - run: yarn --frozen-lockfile --no-progress --non-interactive --prefer-offline
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
